name: Hello workflow
on:
    workflow_call:
      inputs:
        prenom:
          required: true
          type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello ${{ inputs.prenom }} depuis le workflow !"